### ISSUE TITLE
Unable to compile example ans file

### ISSUE THREAD

**Issue by patrickdoodyIRL** [sylvain-prevost/BinaryNotes.NET#1]
Hi,

I am unable to run the sample or test compiler application. The bncompiler does not generate classes. I understand that bncompiler is not your software.

Any ideas?

Running Windows 10

**Java version**
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

 **Exception thrown**
`C:\Users\-----\Downloads\BinaryNotes.NET-master\BinaryNotes.NET-master\Tests>call ..\bncompiler\bnc.cmd -mp ..\cs_xsl_modules -o %OUTPUT_DIR% -ns test.org.bn.coders.test_asn -f test.asn
BinaryNotes compiler v1.5.3
        (c) 2006-2011 Abdulla G. Abdurakhmanov
Current directory: C:\Users\-----\Downloads\BinaryNotes.NET-master\BinaryNotes.NET-master\Tests
Compiling file: test.asn
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:41)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:128)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:203)
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:45)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:87)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:112)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:373)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:228)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:76)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:55)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:132)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:299)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:358)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:323)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:244)
        at org.bn.compiler.Main.createModel(Unknown Source)
        at org.bn.compiler.Main.startForModule(Unknown Source)
        at org.bn.compiler.Main.start(Unknown Source)
        at org.bn.compiler.Main.main(Unknown Source)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @b4c966a`

**Comment by sylvain-prevost** [comment]
Based on the error message, it seems like be stemming from java version incompatibility.

Here is the version that I currently use for this project:

Windows 11

java --version
openjdk 11.0.16.1 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)

I used to run it on Win10 but I do not have this env anymore so I can't tell you which Java version I was using at the time.
(in theory the OS should not matter - acknowledging that in practice it is not always the case).

If you can use the same Java version as I, maybe it'll help.

**Comment by patrickdoodyIRL** [comment]
Thank you Sylvain!
